

server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/austine-namgung/config-server.git
          username: austine-namgung
          password: osc1234!
          clone-on-start: true
  security:
    user:
      name: root
      password: 1234
     
