

server:
  port: 8888

spring:
  application:
    name: vehicle-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/austine-namgung/config-server.git
          username: test
          password: test
          # clone-on-start: true
  security:
    user:
      name: root
      password: 1234
     
